[package]

name = "webrast"
version = "0.1.0"

[[bin]]
name = "webrast"
path = "lib.rs"

[dependencies]
clock_ticks = "*"
euclid = "*"
freetype-rs = "*"
gleam = "*"
glutin = "*"
log = "*"
num_cpus = "*"
rand = "*"

